# Generated by Django 4.2 on 2023-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorInCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_surname', models.TextField()),
                ('mentor_name', models.TextField()),
                ('experience', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('rescued_people', models.FloatField()),
            ],
        ),
    ]
