# Generated by Django 4.2 on 2023-04-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_person_delete_mentorincatalog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
